<?php
/**
 * A simple Zen-Cart products exporter to import them into Jigoshop
 */

/**
 * Important: Edit those settings otherwise the export won't work
 */

/** The name of the database for WordPress */
$db_name = 'zen_cart';

/** MySQL database username */
$db_user = 'username';

/** MySQL database password */
$db_password = 'password';

/** MySQL hostname */
$db_host = 'localhost';

/** Zen-Cart database table prefix */
$db_prefix = 'shop_';

/** URL to the installation folder of WordPress */
$wordpress_url = 'http://www.example.com';

/** URL to the images that should be imported */
$image_url = $wordpress_url . '/wp-content/uploads/import/';

/** tax rate to import the prices with included tax */
$tax_rate = 7.6;

/**
 * That's all, stop editing!
 */

/**
 * Transform string to SEO friendly string
 */
function seo_friendly($string)
{
	$string = preg_replace("`\[.*\]`U","",$string);
	$string = preg_replace('`&(amp;)?#?[a-z0-9]+;`i','-',$string);
	$string = htmlentities($string, ENT_COMPAT, 'utf-8');
	$string = preg_replace( "`&([a-z])(acute|uml|circ|grave|ring|cedil|slash|tilde|caron|lig|quot|rsquo);`i","\\1", $string );
	$string = preg_replace( array("`[^a-z0-9]`i","`[-]+`") , "-", $string);
	
	return strtolower(trim($string, '-'));
}

/**
 * Replace ampersands (&) in a string with ASCII code
 */
function convert_ampersand($string)
{
	return preg_replace('/&([^#])(?![a-z1-4]{1,8};)/i', '&#038;$1', $string);
}

// Output to file or show the export button
if($_POST && $_POST['export']) :
 
	$filename = 'zen-cart-jigoshop.wordpress.' . date('Y-m-d') . '.xml';
	header("Content-Type: text/xml; charset=utf-8");
	header("Content-Disposition: attachment; filename=$filename");
	
	// Connect to the database
	$db_connection = mysql_connect( $db_host, $db_user, $db_password) or die(mysql_error());
	mysql_select_db($db_name, $db_connection) or die(mysql_error());
	
	// Start the xml output
	echo '<?xml version="1.0" encoding="utf-8" ?>'; 

?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->

<!-- generator="Zen-Cart to Jigoshop for Wordpress Exporter" created="<?php echo date('Y-m-d H:m'); ?>" -->
<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.1/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.1/"
>

<channel>
<?php 

	// Configuration
	$c = $db_prefix . 'configuration';
	$query = "SELECT $c.configuration_value 
			  FROM $c 
			  WHERE $c.configuration_key = 'STORE_NAME'";
	
	$result = mysql_query($query) or die(mysql_error());
	$row = mysql_fetch_assoc($result);

?>
	<title><?php echo convert_ampersand($row['configuration_value']); ?></title>
	<link><?php echo $wordpress_url; ?></link>
	<description></description>
	<pubDate><?php echo date('D, d M Y H:m:s') . ' +0000'; ?></pubDate>
	<language>en</language>
	<wp:wxr_version>1.1</wp:wxr_version>
	<wp:base_site_url><?php echo $wordpress_url; ?></wp:base_site_url>
	<wp:base_blog_url><?php echo $wordpress_url; ?></wp:base_blog_url>

	<wp:author><wp:author_id>1</wp:author_id><wp:author_login>admin</wp:author_login><wp:author_email></wp:author_email><wp:author_display_name><![CDATA[admin]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

	<generator>http://wordpress.org/?v=3.2.1</generator>
<?php

	// Products and Images
	$p = $db_prefix . 'products';
	$p_desc = $db_prefix . 'products_description';
	$c_desc = $db_prefix . 'categories_description';
	
	// Get highest id to assign it incrementally to the attachments
	$query = "SELECT max($p.products_id) as products_id
			  FROM $p";
	
	$result = mysql_query($query) or die(mysql_error());
	$row = mysql_fetch_assoc($result);
	$image_id = (int)$row['products_id'] + 1;
	
	// Loop through the products
	$query = "SELECT * 
			  FROM $p 
			  LEFT JOIN $p_desc
			  ON $p.products_id = $p_desc.products_id
			  LEFT JOIN $c_desc
			  ON $p.master_categories_id = $c_desc.categories_id";
	
	$result = mysql_query($query) or die(mysql_error());
	
	while ($row = mysql_fetch_assoc($result)) :	
		$price = number_format((($row['products_price'] / 100) * $tax_rate) + $row['products_price'], 2);
		$data = array(
			'',
			'regular_price' => $price,
			'sale_price' => '',
			'weight' => '',
			'tax_status' => 'taxable',
			'tax_class' => '',
			'stock_status' => 'instock',
			'manage_stock' => 'yes',
			'backorders' => 'no'
		);
	
	?>
	<item>
		<title><?php echo convert_ampersand(utf8_encode($row['products_name'])); ?></title>
		<link><?php echo $wordpress_url . '?product=' . seo_friendly(utf8_encode($row['products_name'])); ?></link>
		<pubDate><?php echo date('D, d M Y H:m:s', strtotime($row['products_date_added'])) . ' +0000'; ?></pubDate>
		<dc:creator>admin</dc:creator>
		<guid isPermaLink="false"><?php echo $wordpress_url . '?post_type=product&#038;p=' . $row['products_id']; ?></guid>
		<description></description>
		<content:encoded><![CDATA[<?php echo utf8_encode(html_entity_decode(strip_tags($row['products_description']))); ?>]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id><?php echo $row['products_id']; ?></wp:post_id>
		<wp:post_date><?php echo $row['products_date_added']; ?></wp:post_date>
		<wp:post_date_gmt><?php echo $row['products_date_added']; ?></wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name><?php echo seo_friendly(utf8_encode($row['products_name'])); ?></wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>product</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="product_cat" nicename="<?php echo seo_friendly(utf8_encode($row['categories_name'])); ?>"><![CDATA[<?php echo utf8_encode($row['categories_name']); ?>]]></category>
		<category domain="product_type" nicename="simple"><![CDATA[simple]]></category>
		<wp:postmeta>
			<wp:meta_key>_edit_last</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>visibility</wp:meta_key>
			<wp:meta_value><![CDATA[visible]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>featured</wp:meta_key>
			<wp:meta_value><![CDATA[no]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sale_price_dates_from</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>sale_price_dates_to</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>price</wp:meta_key>
			<wp:meta_value><![CDATA[<?php echo $price; ?>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>stock</wp:meta_key>
			<wp:meta_value><![CDATA[<?php echo $row['products_quantity']; ?>]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>product_attributes</wp:meta_key>
			<wp:meta_value><![CDATA[a:0:{}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>product_data</wp:meta_key>
			<wp:meta_value><![CDATA[<?php echo serialize($data); ?>]]></wp:meta_value>
		</wp:postmeta>
		<?php if($row['products_image']) : ?>
		<wp:postmeta>
			<wp:meta_key>_thumbnail_id</wp:meta_key>
			<wp:meta_value><![CDATA[<?php echo $image_id; ?>]]></wp:meta_value>
		</wp:postmeta>
		<?php endif; ?>
	</item>
	<?php 
	
		if($row['products_image']) :
			$image_info = pathinfo($row['products_image']);
			$image_name = $image_info['filename']; 
		
	?>
	<item>
		<title><?php echo $image_name; ?></title>
		<link></link>
		<pubDate><?php echo date('D, d M Y H:m:s', strtotime($row['products_date_added'])) . ' +0000'; ?></pubDate>
		<dc:creator>admin</dc:creator>
		<guid isPermaLink="false"></guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id><?php echo $image_id; ?></wp:post_id>
		<wp:post_date><?php echo date('Y-m-d H:m:s'); ?></wp:post_date>
		<wp:post_date_gmt><?php echo date('Y-m-d H:m:s'); ?></wp:post_date_gmt>
		<wp:comment_status>closed</wp:comment_status>
		<wp:ping_status>closed</wp:ping_status>
		<wp:post_name><?php echo $image_name; ?></wp:post_name>
		<wp:status>inherit</wp:status>
		<wp:post_parent><?php echo $row['products_id']; ?></wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type>attachment</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:attachment_url><?php echo $image_url . $row['products_image']; ?></wp:attachment_url>
		<wp:postmeta>
			<wp:meta_key>_wp_attached_file</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_attachment_metadata</wp:meta_key>
			<wp:meta_value></wp:meta_value>
		</wp:postmeta>
	</item>
	<?php 
	
			$image_id++;
	
		endif;

	endwhile;

	mysql_close();

?>
</channel>
</rss>
<?php

else : 

?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Zen-Cart to Jigoshop Exporter</title>
</head>

<body>
	<div>
		<h2>Zen-Cart to Jigoshop Exporter</h2>
		<p>Please make sure to edit the settings in this PHP file before clicking on the button!</p>
		<form method="post">
			<input type="submit" name="export" value="Download Export File" />
		</form>
	</div>
</body>
</html>
<?php

endif;

?>